name: Deploy VIGITEK to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D18DBCF66854886A239B2EFD3DD2C99 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A93EF17F76B47E492FBEA61525A0545 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0399FB54077346FAAC19677A3CD25C25 }}

      - name: Deploy website to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vigitek-web'
          slot-name: 'Production'
          package: .
